module.exports = {
  env: {
    API_OBTENER_TODAS_LAS_CITAS:
      "http://apioptica.recaudo.xyz/public/citas/api/citas",
    API_OBTENER_LAS_CITAS_POR_ESTADO:
      "http://apioptica.recaudo.xyz/public/citas/api/citasestado/",
    API_OBTENER_LAS_CITAS_POR_FECHA:
      "http://apioptica.recaudo.xyz/public/citas/api/citasporfecha/",
    API_OBTENER_TODAS_LAS_CITAS_RESUMIDAS:
      "http://apioptica.recaudo.xyz/public/citas/api/citas_cards",
    API_REGISTRAR_NUEVA_CITA:
      "http://apioptica.recaudo.xyz/public/citas/api/citas/crear_cita",
    API_ACTUALIZAR_CITA:
      "http://apioptica.recaudo.xyz/public/citas/api/citas/update",
    API_OBTENER_TODOS_LOS_PACIENTES:
      "http://apioptica.recaudo.xyz/public/apipacientes/api/pacientes",
    API_GUARDAR_PACIENTE:
      "http://apioptica.recaudo.xyz/public/apipacientes/api/pacientes/nuevo",
    API_CITA_POR_PACIENTE:
      "http://apioptica.recaudo.xyz/public/citas/api/citaporpaciente",
    API_ELIMINAR_PACIENTE:
      "http://apioptica.recaudo.xyz/public/apipacientes/api/pacientes/delete",
    API_ACTUALIZAR_INFORMACION_DEL_PACIENTE:
      "http://apioptica.recaudo.xyz/public/apipacientes/api/pacientes/update/",
    API_CREAR_PRODUCTO:
      "http://apioptica.recaudo.xyz/public/productos/api/productos/addProduct",
    API_OBTENER_TODOS_LOS_PRODUCTOS:
      "http://apioptica.recaudo.xyz/public/productos/api/productos",
    API_ACTUALIZAR_TODOS_LOS_PRODUCTOS:
      "http://apioptica.recaudo.xyz/public/productos/api/productos/update",
    API_ELIMINAR_PRODUCTO:
      "http://apioptica.recaudo.xyz/public/productos/api/productos/delete/",
    API_OBTENER_FACTURAS:
      "http://apioptica.recaudo.xyz/public/contabilidad/api/facturacompleta",
    API_OBTENER_ABONOS_POR_FACTURA:
      "http://apioptica.recaudo.xyz/public/contabilidad/api/abonosfactura/",
    API_REGISTRAR_ABONO:
      "http://apioptica.recaudo.xyz/public/contabilidad/api/facturas/crearabono",
    API_CREAR_FACTURA:
      "http://apioptica.recaudo.xyz/public/contabilidad/api/facturas/crearfactura",
    API_OBTENER_ID_FACTURA:
      "http://apioptica.recaudo.xyz/public/contabilidad/api/facturacodigo/",
    API_CREAR_DETALLE_FACTURA:
      "http://apioptica.recaudo.xyz/public/contabilidad/api/facturas/creardetallefactura",
    API_OBTENER_FACTURA_PERSONA:
      "http://apioptica.recaudo.xyz/public/contabilidad/api/facturacedula/",
    API_OBTENER_DETALLER_POR_FACTURA:
      "http://apioptica.recaudo.xyz/public/contabilidad/api/detallefactura/",
    API_EXPORTAR:
      "http://apioptica.recaudo.xyz/public/contabilidad/api/exportar",
    API_LOGIN:
      "http://apioptica.recaudo.xyz/public/usuarios/api/usuariologin",
    API_CITAS_POR_CEDULA:
      "http://apioptica.recaudo.xyz/public/citas/api/citaporcedula/",
    API_ACTUALIZAR_ESTADO_CITA:
      "http://apioptica.recaudo.xyz/public/contabilidad/api/facturas/actualizarestado/",
  },
};
